{{- range $.Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .name }}-pod
    labels: 
        project: ngp
spec:
    replicas: {{ .replicas }}
    selector: 
        matchLabels:
            app: {{ .name }}-app
    template: 
        metadata: 
            labels: 
                app: {{ .name }}-app
        spec: 
            containers: 
                - name: {{ .name }}-pod
                  image: {{ .image }}:{{ .containerVersion }}
                  ports: 
                    - containerPort: 80
{{- end}}